In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("all_month.csv")

print("Dataset shape:", df.shape)

display(df.head())
display(df.tail())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nSummary statistics:")
display(df.describe())

Dataset shape: (11131, 22)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2026-08-26T02:05:46.773Z,-6.619200,127.546800,10.00,4.50,mb,12.0,127.0,3.138000,0.72,...,2026-08-26T02:21:12.040Z,"218 km NNE of Lospalos, Timor Leste",earthquake,6.47,1.9340,0.180000,9.0,reviewed,us,us
1,2026-08-26T01:58:51.160Z,38.827667,-122.815002,2.16,0.67,md,8.0,77.0,0.005746,0.01,...,2026-08-26T02:00:26.929Z,"8 km NW of The Geysers, CA",earthquake,0.45,1.1800,0.450000,10.0,automatic,nc,nc
2,2026-08-26T01:57:48.740Z,38.825832,-122.813499,2.13,1.91,md,40.0,45.0,0.003617,0.04,...,2026-08-26T02:02:22.450Z,"7 km NW of The Geysers, CA",earthquake,0.17,0.2500,0.160000,42.0,automatic,nc,nc
3,2026-08-26T01:44:33.400Z,20.153000,-156.341995,5.58,2.15,md,24.0,299.0,0.531600,0.14,...,2026-08-26T01:48:08.230Z,"54 km W of Hāwī, Hawaii",earthquake,6.25,6.7800,0.110561,12.0,automatic,hv,hv
4,2026-08-26T01:32:22.839Z,61.492000,-151.562000,98.90,2.30,ml,68.0,65.0,0.100000,0.70,...,2026-08-26T01:36:02.673Z,"46 km NNW of Beluga, Alaska",earthquake,2.80,2.1775,0.200000,46.0,automatic,ak,ak

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
11126,2026-07-27T03:04:58.930Z,19.469500,-155.179504,39.110001,1.87,md,7.0,303.0,0.077510,0.08,...,2026-07-27T03:08:31.580Z,"4 km W of Fern Forest, Hawaii",earthquake,2.71,2.7200,0.202219,17.0,automatic,hv,hv
11127,2026-07-27T03:04:21.833Z,-24.731700,-175.218400,10.000000,4.50,mb,14.0,140.0,38.899000,0.65,...,2026-08-05T04:01:29.040Z,south of Tonga,earthquake,16.41,1.9200,0.156000,12.0,reviewed,us,us
11128,2026-07-27T02:57:31.280Z,40.540333,-124.302667,28.460000,1.84,md,31.0,112.0,0.039880,0.11,...,2026-08-05T10:12:56.420Z,"5 km SW of Ferndale, CA",earthquake,0.37,0.7200,0.212000,20.0,reviewed,nc,nc
11129,2026-07-27T02:56:26.002Z,61.759000,-148.668000,8.700000,1.40,ml,16.0,124.0,0.100000,0.70,...,2026-07-27T21:57:56.772Z,"5 km ESE of Sutton-Alpine, Alaska",earthquake,3.80,2.3968,0.100000,13.0,reviewed,ak,ak
11130,2026-07-27T02:56:10.029Z,35.123167,-97.911000,11.000000,0.69,ml,16.0,209.0,0.033293,0.24,...,2026-08-05T17:20:28.271Z,"5 km SW of Amber, Oklahoma",earthquake,NaN,1.3000,0.250000,6.0,reviewed,ok,ok

Column names:
['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst', 'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type', 'horizontalError', 'depthError', 'magError', 'magNst', 'status', 'locationSource', 'magSource']

Data types:
time                   str
latitude           float64
longitude          float64
depth              float64
mag                float64
magType                str
nst                float64
gap                float64
dmin               float64
rms                float64
net                    str
id                     str
updated                str
place                  str
type                   str
horizontalError    float64
depthError         float64
magError           float64
magNst             float64
status                 str
locationSource         str
magSource              str
dtype: object

Summary statistics:

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,11131.000000,11131.000000,11131.000000,11128.000000,11130.000000,11130.000000,11117.000000,11130.000000,10759.000000,11082.000000,11088.000000,11126.000000
mean,38.709916,-104.677986,20.361751,1.681645,25.666217,115.492273,0.524302,0.315598,3.297378,2.710607,0.175208,18.847924
std,18.139836,81.794642,49.449210,1.284496,22.901758,69.641197,1.622703,0.304205,5.912354,5.073847,0.094525,28.993865
min,-65.601200,-179.922600,-3.410000,-1.250000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.268000,-152.142000,3.330000,0.820000,12.000000,64.000000,0.027370,0.100000,0.280000,0.510000,0.100000,7.000000
50%,38.608333,-121.334500,7.592800,1.470000,19.000000,91.000000,0.080180,0.200000,0.690000,1.030000,0.161590,12.000000
75%,51.960350,-111.285250,14.100000,2.200000,32.000000,154.000000,0.400000,0.500000,4.300000,2.433350,0.207186,20.000000
max,81.462300,179.992000,665.326000,7.700000,281.000000,354.000000,38.899000,5.600000,105.700000,61.834100,0.894122,863.000000

In [11]:
# Missing-value report
missing_report = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage":
        (df.isnull().sum() / len(df) * 100).round(2)
})

display(
    missing_report.sort_values(
        "missing_percentage",
        ascending=False
    )
)

print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df["id"].duplicated().sum())

categorical_columns = [
    "magType",
    "type",
    "status",
    "locationSource",
    "magSource"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False))
    
    
range_columns = [
    "latitude",
    "longitude",
    "depth",
    "mag",
    "nst",
    "gap",
    "dmin",
    "rms"
]

for column in range_columns:
    print(
        column,
        "Min:", df[column].min(),
        "Max:", df[column].max()
    )

                 missing_count  missing_percentage
horizontalError            372                3.34
depthError                  49                0.44
magError                    43                0.39
dmin                        14                0.13
magNst                       5                0.04
mag                          3                0.03
magType                      3                0.03
nst                          1                0.01
gap                          1                0.01
rms                          1                0.01
longitude                    0                0.00
depth                        0                0.00
time                         0                0.00
latitude                     0                0.00
place                        0                0.00
updated                      0                0.00
id                           0                0.00
net                          0                0.00
type                         0                0.00
status                       0                0.00
locationSource               0                0.00
magSource                    0                0.00

Duplicate rows: 0
Duplicate IDs: 0

magType
magType
ml       7174
md       2796
mb        991
mww       115
mwr        16
mh         16
mw         10
mb_lg       8
NaN         3
mun         1
mwb         1
Name: count, dtype: int64

type
type
earthquake                10867
quarry blast                174
explosion                    74
ice quake                     9
landslide                     3
other event                   2
mining explosion              1
experimental explosion        1
Name: count, dtype: int64

status
status
reviewed     9692
automatic    1439
Name: count, dtype: int64

locationSource
locationSource
ak    2208
nc    1868
ci    1785
us    1453
av     879
tx     872
hv     455
uu     447
uw     369
ok     252
pr     248
mb     133
nn     118
nm      31
se      13
Name: count, dtype: int64

magSource
magSource
ak     2208
nc     1868
ci     1785
us     1452
av      879
tx      872
hv      455
uu      447
uw      369
ok      252
pr      248
mb      133
nn      118
nm       31
se       13
slm       1
Name: count, dtype: int64
latitude Min: -65.6012 Max: 81.4623
longitude Min: -179.9226 Max: 179.992
depth Min: -3.41 Max: 665.326
mag Min: -1.25 Max: 7.7
nst Min: 0.0 Max: 281.0
gap Min: 12.0 Max: 354.0
dmin Min: 0.0 Max: 38.899
rms Min: 0.0 Max: 5.6